api_key: devkey
api_secret: secret12345678
ws_url: ws://127.0.0.1:7880
redis:
  address: 127.0.0.1:6379
sip_port: 5060
nat_1_to_1_ip: 13.135.81.172
media_nat_1_to_1_ip: 13.135.81.172
rtp_port: 10000-10100

# Authentication for Twilio SIP Trunk
auth:
  credentials:
    - username: osteo-twilio
      password: twilio123456
    - username: twilio
      password: twilio123456

logging:
  level: debug
